export const settings = {
  rebus_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    reset: true,
    soundOrNext: false,
  },
  audio_abc_content: {
    panelShow: true,
    help: false,
    check: false,
    next: false,
    status: false,
    soundOrNext: true,
  },
  video_info_content: {
    panelShow: true,
    help: false,
    check: false,
    next: false,
    status: false,
    soundOrNext: false,
  },
  quiz_swow_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    reset: true,
    soundOrNext: false,
  },
  puzzle_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    reset: true,
    soundOrNext: false,
  },
  info_content: {
    panelShow: true,
    help: false,
    check: false,
    next: false,
    status: false,
    soundOrNext: true,
  },
  quiz_sentence_content: {
    panelShow: true,
    help: true,
    check: false,
    next: true,
    reset: true,
    soundOrNext: false,
  },
  quiz_img_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  quiz_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  audio_book_content: {
    panelShow: true,
    help: false,
    check: false,
    next: false,
    status: false,
    soundOrNext: true,
    book: true,
  },
  draw_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    reset: true,
    soundOrNext: false,
  },
  memory_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  fillwords_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  picture_order_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  row_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  make_word_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  bubble_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  find_pair_content: {
    panelShow: true,
    help: false,
    check: false,
    next: true,
    soundOrNext: false,
  },
  
}